---
title: "Band Recoveries Exploration"
author: "Cameryn Brock"
date: "3/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(here)
library(janitor)
library(sf)

```


```{r}

recoveries <- read_csv(here::here("RawData", "Recoveries.csv")) %>% 
  clean_names() 

rec <- recoveries %>% 
  select(!c(long_band, lat_band, date_banded, location_banded)) %>% 
  rename("lat" = "lat_rec",
         "lon" = "long_rec",
         "location" = "recovery_location_descr",
         "date" = "date_recovered") %>% 
  mutate("band_rec" = "recovered") %>% 
  mutate(date = lubridate::mdy(date)) %>% 
  select(band_number, species, band_rec, date, age, sex, location, notes, lon, lat)

band <- recoveries %>% 
  select(!c(long_rec, lat_rec, date_recovered, recovery_location_descr)) %>% 
  rename("lat" = "lat_band",
         "lon" = "long_band",
         "location" = "location_banded",
         "date" = "date_banded") %>% 
  mutate("band_rec" = "banded") %>% 
  mutate(date = lubridate::mdy(date)) %>% 
  select(band_number, species, band_rec, date, age, sex, location, notes, lon, lat)

recoveries_tidy <- bind_rows(rec, band) %>% 
  arrange(band_number, date) 

sf <- st_as_sf(recoveries_tidy,
               coords = c("lon", "lat"),
               crs = 4326)

```

